[package]
name = "smaa"
version = "0.5.0"
authors = ["Jonathan Behrens <fintelia@gmail.com>"]
description = "A library for post process antialiasing using SMAA"
repository = "https://github.com/fintelia/gfx_smaa"
keywords = ["graphics", "antialiasing", "SMAA"]
categories = ["rendering", "game-engines"]
license = "MIT"
edition = "2021"

[dependencies]
env_logger = "0.9.0"
shaderc = "0.7.3"
wgpu = { version = "0.12", features = ["spirv"] }

[dev-dependencies]
winit = "0.26.0"
futures = "0.3.16"
