[package]
name = "smaa"
version = "0.11.0"
authors = ["Jonathan Behrens <fintelia@gmail.com>"]
description = "A library for post process antialiasing using SMAA"
repository = "https://github.com/fintelia/smaa-rs"
keywords = ["graphics", "antialiasing", "SMAA"]
categories = ["rendering", "game-engines"]
license = "MIT"
edition = "2021"

[dependencies]
naga = "0.13"
wgpu = { version = "0.17", features = ["glsl"] }

[dev-dependencies]
winit = "0.28.1"
futures = "0.3.26"
